In [1]:
from google.colab import drive

In [2]:
drive.mount('../content/drive')

Mounted at ../content/drive


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
dataset=pd.read_csv('../content/drive/MyDrive/Colab Notebooks/bodyfat.csv')

In [5]:
dataset.head()

Density  BodyFat  Age  Weight  Height  Neck  Chest  Abdomen    Hip  Thigh  \
0   1.0708     12.3   23  154.25   67.75  36.2   93.1     85.2   94.5   59.0   
1   1.0853      6.1   22  173.25   72.25  38.5   93.6     83.0   98.7   58.7   
2   1.0414     25.3   22  154.00   66.25  34.0   95.8     87.9   99.2   59.6   
3   1.0751     10.4   26  184.75   72.25  37.4  101.8     86.4  101.2   60.1   
4   1.0340     28.7   24  184.25   71.25  34.4   97.3    100.0  101.9   63.2   

   Knee  Ankle  Biceps  Forearm  Wrist  
0  37.3   21.9    32.0     27.4   17.1  
1  37.3   23.4    30.5     28.9   18.2  
2  38.9   24.0    28.8     25.2   16.6  
3  37.3   22.8    32.4     29.4   18.2  
4  42.2   24.0    32.2     27.7   17.7

In [10]:
df1=dataset.drop(['Density'],axis='columns')
df1.head()

BodyFat  Age  Weight  Height  Neck  Chest  Abdomen    Hip  Thigh  Knee  \
0     12.3   23  154.25   67.75  36.2   93.1     85.2   94.5   59.0  37.3   
1      6.1   22  173.25   72.25  38.5   93.6     83.0   98.7   58.7  37.3   
2     25.3   22  154.00   66.25  34.0   95.8     87.9   99.2   59.6  38.9   
3     10.4   26  184.75   72.25  37.4  101.8     86.4  101.2   60.1  37.3   
4     28.7   24  184.25   71.25  34.4   97.3    100.0  101.9   63.2  42.2   

   Ankle  Biceps  Forearm  Wrist  
0   21.9    32.0     27.4   17.1  
1   23.4    30.5     28.9   18.2  
2   24.0    28.8     25.2   16.6  
3   22.8    32.4     29.4   18.2  
4   24.0    32.2     27.7   17.7

In [11]:
df1.shape

(252, 14)

In [12]:
df1.isnull().sum()

BodyFat    0
Age        0
Weight     0
Height     0
Neck       0
Chest      0
Abdomen    0
Hip        0
Thigh      0
Knee       0
Ankle      0
Biceps     0
Forearm    0
Wrist      0
dtype: int64

In [24]:
dummies=pd.get_dummies(df1.Age)
dummies

22  23  24  25  26  27  28  29  30  31  ...  64  65  66  67  68  69  70  \
0     0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3     0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4     0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
247   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   
248   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
249   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
250   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
251   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     72  74  81  
0     0   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
247   0   0   0  
248   1   0   0  
249   1   0   0  
250   1   0   0  
251   0   1   0  

[252 rows x 51 columns]

In [25]:
df2=pd.concat([df1,dummies],axis='columns')
df2.head()

BodyFat  Age  Weight  Height  Neck  Chest  Abdomen    Hip  Thigh  Knee  \
0     12.3   23  154.25   67.75  36.2   93.1     85.2   94.5   59.0  37.3   
1      6.1   22  173.25   72.25  38.5   93.6     83.0   98.7   58.7  37.3   
2     25.3   22  154.00   66.25  34.0   95.8     87.9   99.2   59.6  38.9   
3     10.4   26  184.75   72.25  37.4  101.8     86.4  101.2   60.1  37.3   
4     28.7   24  184.25   71.25  34.4   97.3    100.0  101.9   63.2  42.2   

   ...  64  65  66  67  68  69  70  72  74  81  
0  ...   0   0   0   0   0   0   0   0   0   0  
1  ...   0   0   0   0   0   0   0   0   0   0  
2  ...   0   0   0   0   0   0   0   0   0   0  
3  ...   0   0   0   0   0   0   0   0   0   0  
4  ...   0   0   0   0   0   0   0   0   0   0  

[5 rows x 65 columns]

In [26]:
df2.Age.unique()

array([23, 22, 26, 24, 25, 27, 32, 30, 35, 34, 28, 33, 31, 29, 41, 49, 40,
       50, 46, 45, 44, 48, 39, 43, 47, 51, 42, 54, 58, 62, 61, 56, 57, 55,
       69, 81, 66, 67, 64, 70, 72, 53, 38, 52, 36, 37, 60, 63, 65, 68, 74])

In [27]:
x=df1.drop('Age', axis='columns')
x.shape

(252, 13)

In [28]:
y=df1['Age']
y.shape

(252,)

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=20)

In [30]:
from sklearn.linear_model import LogisticRegression
model2=LogisticRegression()
model2.fit(x_train,y_train)
model2.score(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.2736318407960199

LINEAR REGRESSION

In [32]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Density  252 non-null    float64
 1   BodyFat  252 non-null    float64
 2   Age      252 non-null    int64  
 3   Weight   252 non-null    float64
 4   Height   252 non-null    float64
 5   Neck     252 non-null    float64
 6   Chest    252 non-null    float64
 7   Abdomen  252 non-null    float64
 8   Hip      252 non-null    float64
 9   Thigh    252 non-null    float64
 10  Knee     252 non-null    float64
 11  Ankle    252 non-null    float64
 12  Biceps   252 non-null    float64
 13  Forearm  252 non-null    float64
 14  Wrist    252 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 29.7 KB


In [33]:
dataset

Density  BodyFat  Age  Weight  Height  Neck  Chest  Abdomen    Hip  \
0     1.0708     12.3   23  154.25   67.75  36.2   93.1     85.2   94.5   
1     1.0853      6.1   22  173.25   72.25  38.5   93.6     83.0   98.7   
2     1.0414     25.3   22  154.00   66.25  34.0   95.8     87.9   99.2   
3     1.0751     10.4   26  184.75   72.25  37.4  101.8     86.4  101.2   
4     1.0340     28.7   24  184.25   71.25  34.4   97.3    100.0  101.9   
..       ...      ...  ...     ...     ...   ...    ...      ...    ...   
247   1.0736     11.0   70  134.25   67.00  34.9   89.2     83.6   88.8   
248   1.0236     33.6   72  201.00   69.75  40.9  108.5    105.0  104.5   
249   1.0328     29.3   72  186.75   66.00  38.9  111.1    111.5  101.7   
250   1.0399     26.0   72  190.75   70.50  38.9  108.3    101.3   97.8   
251   1.0271     31.9   74  207.50   70.00  40.8  112.4    108.5  107.1   

     Thigh  Knee  Ankle  Biceps  Forearm  Wrist  
0     59.0  37.3   21.9    32.0     27.4   17.1  
1     58.7  37.3   23.4    30.5     28.9   18.2  
2     59.6  38.9   24.0    28.8     25.2   16.6  
3     60.1  37.3   22.8    32.4     29.4   18.2  
4     63.2  42.2   24.0    32.2     27.7   17.7  
..     ...   ...    ...     ...      ...    ...  
247   49.6  34.8   21.5    25.6     25.7   18.5  
248   59.6  40.8   23.2    35.2     28.6   20.1  
249   60.3  37.3   21.5    31.3     27.2   18.0  
250   56.0  41.6   22.7    30.5     29.4   19.8  
251   59.3  42.2   24.6    33.7     30.0   20.9  

[252 rows x 15 columns]

In [34]:
dataset.isnull().sum()

Density    0
BodyFat    0
Age        0
Weight     0
Height     0
Neck       0
Chest      0
Abdomen    0
Hip        0
Thigh      0
Knee       0
Ankle      0
Biceps     0
Forearm    0
Wrist      0
dtype: int64

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
label=LabelEncoder()
dataset['label'] = label.fit_transform(dataset["Age"])

In [37]:
x=dataset.drop(['BodyFat','Age'],axis=1)

In [38]:
x

Density  Weight  Height  Neck  Chest  Abdomen    Hip  Thigh  Knee  Ankle  \
0     1.0708  154.25   67.75  36.2   93.1     85.2   94.5   59.0  37.3   21.9   
1     1.0853  173.25   72.25  38.5   93.6     83.0   98.7   58.7  37.3   23.4   
2     1.0414  154.00   66.25  34.0   95.8     87.9   99.2   59.6  38.9   24.0   
3     1.0751  184.75   72.25  37.4  101.8     86.4  101.2   60.1  37.3   22.8   
4     1.0340  184.25   71.25  34.4   97.3    100.0  101.9   63.2  42.2   24.0   
..       ...     ...     ...   ...    ...      ...    ...    ...   ...    ...   
247   1.0736  134.25   67.00  34.9   89.2     83.6   88.8   49.6  34.8   21.5   
248   1.0236  201.00   69.75  40.9  108.5    105.0  104.5   59.6  40.8   23.2   
249   1.0328  186.75   66.00  38.9  111.1    111.5  101.7   60.3  37.3   21.5   
250   1.0399  190.75   70.50  38.9  108.3    101.3   97.8   56.0  41.6   22.7   
251   1.0271  207.50   70.00  40.8  112.4    108.5  107.1   59.3  42.2   24.6   

     Biceps  Forearm  Wrist  label  
0      32.0     27.4   17.1      1  
1      30.5     28.9   18.2      0  
2      28.8     25.2   16.6      0  
3      32.4     29.4   18.2      4  
4      32.2     27.7   17.7      2  
..      ...      ...    ...    ...  
247    25.6     25.7   18.5     47  
248    35.2     28.6   20.1     48  
249    31.3     27.2   18.0     48  
250    30.5     29.4   19.8     48  
251    33.7     30.0   20.9     49  

[252 rows x 14 columns]

In [39]:
y=dataset['BodyFat']
y.unique()

array([12.3,  6.1, 25.3, 10.4, 28.7, 20.9, 19.2, 12.4,  4.1, 11.7,  7.1,
        7.8, 20.8, 21.2, 22.1, 29. , 22.9, 16. , 16.5, 19.1, 15.2, 15.6,
       17.7, 14. ,  3.7,  7.9,  8.8, 11.9,  5.7, 11.8, 21.3, 32.3, 40.1,
       24.2, 28.4, 35.2, 32.6, 34.5, 32.9, 31.6, 32. ,  7.7, 13.9, 10.8,
        5.6, 13.6,  4. , 10.2,  6.6,  8. ,  6.3,  3.9, 22.6, 20.4, 28. ,
       31.5, 24.6, 26.1, 29.8, 30.7, 25.8, 30. , 21.5, 13.8, 12.9, 24.3,
        8.5, 13.5, 18.5, 22.2, 18.8, 31.4, 26.8, 18.4, 27. , 26.6, 14.9,
       23.1,  8.3, 14.1, 20.5, 18.2, 24.9,  9. , 17.4,  9.6, 11.3, 17.8,
       20.1, 22.3, 25.4, 18. , 19.3, 18.3, 17.3, 21.4, 19.7, 26.7, 16.7,
       18.1, 27.9, 14.7, 17.5, 27.2, 22.7, 23.6, 24.4, 27.1, 21.8, 29.4,
       22.4, 23.3,  9.4, 10.3, 14.2, 29.6,  5.3, 25.2, 19.6, 10.1, 21. ,
       31.2, 10. , 12.5, 22.5, 14.6, 13. , 15.1, 27.3, 20.3, 34.3,  3. ,
        0.7, 16.9,  9.9, 13.1, 29.9,  0. , 11.5, 12.1,  8.6, 11.4, 38.1,
       15.9, 24.7, 22.8, 25.5, 22. , 12.2,  6. , 34

In [40]:
x.shape,y.shape

((252, 14), (252,))

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=20)

In [42]:
x_train.shape, y_train.shape

((201, 14), (201,))

In [43]:
x_test.shape,y_test.shape

((51, 14), (51,))

In [44]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [45]:
y_predict = model.predict(x_test)

In [46]:
y_predict

array([31.28553716, 21.4639822 , 25.28591379,  3.6846025 ,  7.3288101 ,
       20.19709454, 25.47209883, 11.66789195, 32.17251707, 21.00395262,
       18.70752046, 18.36291402, 22.7946216 , 12.97984389, 20.87777373,
       15.22545298, 21.22195047, 35.2807066 , 25.17858693,  9.31362706,
       14.41568498, 12.39506266, 26.27274223, 30.4012037 , 21.82992983,
       21.87986982, 34.5538409 , 32.30283409, 19.88971248, 19.41730617,
       23.76632274, 24.5289967 , 16.90215691, 22.71670109,  9.23054133,
       45.20169226, 21.22601932, 29.44500129, 25.13911537, 13.88370726,
       12.10392251,  6.31143588, 13.64515396, 17.56238505, 11.85187604,
       13.67526911, 21.34956381, 16.17166572, 24.5330619 ,  6.42784633,
       25.37929203])

In [50]:
from sklearn.metrics import accuracy_score
input= [[28.43,6.56,3.56,7.00,9.87,8.98,6.87,16.88,24.44,31.09,19.12,14.79,29.33,0]]

In [51]:
temp=model.predict(input)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [52]:
temp

array([-11275.65647116])

In [53]:
from sklearn.metrics import mean_absolute_error
error=mean_absolute_error(y_test,y_predict)


In [54]:
error

0.5519885471499952

In [55]:
from sklearn.metrics import mean_squared_error
Mean_sq= mean_squared_error(y_test,y_predict)

In [56]:
Mean_sq

1.8021063136657165

In [58]:
import math
rmse = math.sqrt(Mean_sq)

In [59]:
rmse

1.3424255337506497

In [60]:
from sklearn.metrics import r2_score

In [61]:
temp2=r2_score(y_predict,y_test)

In [62]:
temp2

0.9737923203732665